# Generated by Django 5.0.6 on 2024-07-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='csvs')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
    ]
