# Generated by Django 5.0.6 on 2024-07-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0005_remove_csv_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='nome',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
