# Generated by Django 5.0.6 on 2024-07-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0002_selecionados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Selecionados',
        ),
    ]
