# Generated by Django 5.0.6 on 2024-07-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0004_selecionados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Selecionados',
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='texto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
