# Generated by Django 5.0.6 on 2024-07-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0006_remove_mensagem_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='texto',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Invitee Email'),
        ),
    ]
