# Generated by Django 5.0.6 on 2024-07-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0007_mensagem_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='ativo',
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='texto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
