# Generated by Django 5.0.6 on 2024-07-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0008_remove_mensagem_ativo_alter_mensagem_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='mensagem')),
            ],
        ),
        migrations.DeleteModel(
            name='mensagem',
        ),
    ]
