# Generated by Django 5.0.6 on 2024-08-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0011_alter_imagem_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=1000)),
                ('sucesso', models.IntegerField()),
                ('erro', models.IntegerField()),
                ('dataEnvio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
