# Generated by Django 5.0.6 on 2024-08-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0012_controle'),
    ]

    operations = [
        migrations.AddField(
            model_name='controle',
            name='img',
            field=models.ImageField(default=None, upload_to=None),
        ),
    ]
