# Generated by Django 5.0.6 on 2024-08-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0013_controle_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='img',
            field=models.ImageField(default=False, upload_to=None),
        ),
    ]
