# Generated by Django 5.0.6 on 2024-07-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='contato',
            field=models.PositiveIntegerField(),
        ),
    ]
