# Generated by Django 5.0.6 on 2024-07-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_alter_contato_contato_alter_contato_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='gestor',
        ),
    ]
