# Generated by Django 5.0.6 on 2024-07-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_remove_contato_gestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='contato',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
