# Generated by Django 5.0.6 on 2024-07-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0006_alter_contato_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='enviar',
            field=models.BooleanField(default=False),
        ),
    ]
