# Generated by Django 5.0.6 on 2024-07-16 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0007_contato_enviar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='enviar',
            new_name='selecionado',
        ),
    ]
